spring.application.name=Enotes_API_Service
spring.thymeleaf.cache=false
server.port=8081
#postgresql connexion
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
#show sql
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

file.upload.path=notes/

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#email send configuration for gmail
#spring.mail.host=smtp.gmail.com
#spring.mail.username=brand10.tap09@gmail.com
#spring.mail.password=nflw mgjz qlld huay
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#email send configuration for local mailpit server
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mapache@prueba.com
#spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

